server:
    port: 8888

spring:
    application:
        name: spring-cloud-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/sparklingshines/spring-cloud-lerning     # 配置git仓库的地址
                    search-paths: config-repository                       # git仓库地址下的相对地址，可以配置多个，用,分割。
                    username:                                             # git仓库的账号
                    password:                                             # git仓库的密码
#spring.profiles.active=native #默认从应用的src/main/resource目录下检索配置文件
#spring.cloud.config.server.native.searchLocations=file:E:/properties/ #指定配置文件的位置


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/   ## 注册中心eurka地址